### PR TITLE
Use Array.isArray() instead of internal "_isArray" function

### PR DESCRIPTION
**Pull request by lucasrmendonca**
### Description, Motivation and Context
- Internal _isArray function had a useless Boolean conversion (!!obj) that was always true because all Arrays (even an empty one) evaluate to Truthy.

### What kind of change does this PR introduce?

- [x] Refactoring

### Checklist:

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [x] Overall test coverage is not decreased.
- [x] All new and existing tests passed.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by KSDaemon** [comment]
@lucasrmendonca Is `_isArray` now being used somewhere?

**Comment by lucasrmendonca** [comment]
> @lucasrmendonca Is `_isArray` now being used somewhere?

Nope, I decided to remove the method entirely and use just Array.isArray() instead

**Comment by KSDaemon** [comment]
Ok! Looks good! Just need to resolve the conflicts (after previous merge) ;)

**Comment by lucasrmendonca** [comment]
Also, is there any advantage of adding internal utility functions to the Wampy class instead of declaring them in another file such as utils.js ?

**Comment by KSDaemon** [comment]
> Also, is there any advantage of adding internal utility functions to the Wampy class instead of declaring them in another file such as utils.js ?

Nop. I was thinking about extracting all those not bind to the wampy instance helpers out of wampy class to reduce memory footprint.

**Comment by KSDaemon** [comment]
👍🏻 Cool! Merging!

**Pull request merged**
