### PR TITLE
Progressive calls

### PR DESCRIPTION
**Pull request by KSDaemon**
This PR introduces new feature: progressive call invocations (don't mess with progressive call results).

So now you can not only get results in chunks, but also send payload for stored procedure in chunks.

This refs and closes https://github.com/KSDaemon/wampy.js/issues/183

- **Created a progressiveCall public API function for making progressive calls**
- **Fix wampy cli test mock**
- **Some code improvements and refactoring**
- **Fix progress flag processing during progressive call invocation**
- **Add tests for progressive call invocations**
- **Fix progressiveCall to be non async**
- **Fix progressiveCall tests to be non async**
- **Add docs about progressiveCall() API**

### What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no new functionality, only code improvements)

### Checklist:

- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] Overall test coverage is not decreased.
- [x] All new and existing tests passed.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by KSDaemon** [comment]
@lucasrmendonca (or anyone else) Maybe you can have a look. Having another pair of eyes on the new code will be good. Ping me if you'll have any feedback! Thnx in advance!

**Comment by KSDaemon** [comment]
Okay. I'll merge it as is.

**Comment by lucasrmendonca** [comment]
Hi, sorry for the late answer, I'm currently on vacation 🌴

**Comment by KSDaemon** [comment]
@lucasrmendonca oh great! No worries! Have a great time!

**Pull request merged**
