### PR TITLE
#4 allow return Promise in register rpc

### PR DESCRIPTION
**Pull request by darrrk**

### CODE REVIEW

**Comment by KSDaemon** [comment]
Hey! Looks pretty good! Thanks for PR! Will include this in next release ;)

**Comment by darrrk** [comment]
Thanks! ;)
Don't forget to point in documentation about [es6-promise](https://github.com/jakearchibald/es6-promise) for [unsupported stack](http://caniuse.com/#search=promise)
I hope this feature help me release next version of [backbone.wamp](https://github.com/darrrk/backbone.wamp), which based on wampy! :)

**Comment by KSDaemon** [comment]
Yep! I'll also update tests for that case.
Don't hear yet about backbone.wamp! Cool! I was thinking about something like that, 'cause i use backbone by myself.

**Comment by darrrk** [comment]
> Yep! I'll also update tests for that case.

I wanted to include it to PR, but I don't understand how imitate Promise in static WebSocket messages. In backbone.wamp I use real environment browser <-> nodejs for testing, but has problems with travis ci integration. Yet... Cool idea for your test too.

> Don't hear yet about backbone.wamp! Cool! I was thinking about something like that, 'cause i use backbone by myself.

Cool! My roadmap to release 2.x version:
* remove CoffeeScript
* unregister feature
* travis ci integration
* freeze it for autobahn support

And later release 3.x version, which will use wampy instead autobahn. It's seems more compact and clever ;)

**Comment by KSDaemon** [comment]
@darrrk great plans! Good luck! And yes, cs — sucks :)

**Pull request merged**
